-- MySQL/MariaDB counterpart of
-- sqlite/20260831000002_cross_repo_pull_requests.up.sql.
--
-- Lifts the same-repository restriction on pull requests (H4 / Phase 5).
-- MariaDB (the backend this workspace targets — CI runs `mariadb:12.3.3`)
-- names an unnamed *table-level* CHECK `CONSTRAINT_1` (column-level checks
-- keep their column name: `state`, `merge_strategy`, `close_reason`), so
-- the table constraint from the original migration is `CONSTRAINT_1`.
-- `DROP CONSTRAINT IF EXISTS` (MariaDB 10.2.22+) keeps a fresh-database
-- run from erroring if the constraint is somehow absent.
ALTER TABLE pull_requests DROP CONSTRAINT IF EXISTS `CONSTRAINT_1`;
